### ISSUE TITLE
Feature-request: exclude unused names

### ISSUE THREAD

**Issue by wimglenn** [asmeurer/removestar#32]
Nice tool, thanks!

How about an option to exclude names which aren't actually used by the importing module - so similar like the tool already does, but then prunes all the "unused imports"?

I appreciate this would be about as difficult as the halting problem in the general case, so just a "best-effort" attempt would be good enough.

**Comment by asmeurer** [comment]
This should be how it already works. It replaces `import *` with just the names that are actually used in the module. Do you have an example where it doesn't behave like this?

**Comment by wimglenn** [comment]
Hmm, when it was used on a big and messy codebase a while ago I had to manually remove a few unused names. But when I try to create a minimal reproducer today, I can't, it's working as expected! I'll just close the issue, and if I see this happen again I'll be sure to check more carefully what's going on.

**Comment by asmeurer** [comment]
This uses pyflakes under the hood to detect which names are used. If you use something too dynamic it won't be able to detect things correctly. Otherwise it's more likely a bug in pyflakes rather than removestar, although I wouldn't rule out a bug here as I haven't really touched this codebase in a while.
